version: '3.8'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/inscripciones

  ingesta:
    build: ./ingesta
    environment:
      - API_URL=http://app:3000
      - S3_BUCKET=inscripciones-data-2025-camila
      - AWS_REGION=us-east-1
    volumes:
      - ~/.aws:/root/.aws:ro  # Para credenciales AWS
    depends_on:
      - app
    profiles: ["ingesta"]  # Solo se ejecuta cuando se especifica

volumes:
  mongo_data: